@startuml
!include Style.puml

participant ":CardCollector" as CardCollector
participant ":CommandContext" as CommandContext COMMANDCONTEXT_COLOR_PRIMARY
participant ":Parser" as Parser PARSER_COLOR_PRIMARY
participant ":UndoCommand" as UndoCommand COMMAND_COLOR_PRIMARY
participant ":Command" as Command COMMAND_COLOR_PRIMARY
participant ":Ui" as Ui UI_COLOR_PRIMARY

-> CardCollector : input "undo"

activate CardCollector
CardCollector -> Parser : parse(input)
activate Parser

create UndoCommand
Parser -> UndoCommand
activate UndoCommand
UndoCommand --> Parser : command
deactivate UndoCommand

Parser --> CardCollector : command
deactivate Parser
CardCollector -[hidden]-> Parser

create CommandContext
CardCollector -> CommandContext
activate CommandContext
CommandContext --> CardCollector : context
deactivate CommandContext

CardCollector -> UndoCommand : execute(context)
activate UndoCommand

UndoCommand -> CommandContext : getCommandHistory()
activate CommandContext
CommandContext --> UndoCommand : commandHistory (Stack)
deactivate CommandContext

alt commandHistory is empty
    UndoCommand -> Ui : echo("Nothing to undo.")
    activate Ui
    Ui --> UndoCommand
    deactivate Ui

    UndoCommand --> CardCollector : commandResult
else commandHistory is not empty
    UndoCommand -> CommandContext : commandHistory.pop()
    activate CommandContext
    CommandContext --> UndoCommand : lastCommand
    deactivate CommandContext

    UndoCommand -> Command : undo(context)
    activate Command

    Command -> Ui : printUndoSuccess(targetList)
    activate Ui
    Ui --> Command
    deactivate Ui

    Command --> UndoCommand : commandResult
    deactivate Command
end

UndoCommand --> CardCollector : commandResult
deactivate UndoCommand
CardCollector -[hidden]-> Parser

<-- CardCollector
deactivate CardCollector

destroy CommandContext
destroy UndoCommand

@enduml